"""Build Enhanced_nb.ipynb - correlation analysis + duplicate/redundant column detection pipeline."""
import json
from pathlib import Path

NB_PATH = Path(r'd:\DS\kaggle\PSTU_Datathon\Enhanced_nb.ipynb')
DATA = r'd:\DS\kaggle\PSTU_Datathon'


def md(*lines):
    return {
        "cell_type": "markdown",
        "id": next_id(),
        "metadata": {"language": "markdown"},
        "source": "".join(l if l.endswith("\n") else l + "\n" for l in lines),
    }


def code(*lines):
    return {
        "cell_type": "code",
        "id": next_id(),
        "metadata": {"language": "python"},
        "execution_count": None,
        "source": "".join(l if l.endswith("\n") else l + "\n" for l in lines),
        "outputs": [],
    }


import itertools
_id_counter = itertools.count()
def next_id():
    return f"cell-{next(_id_counter):04d}"


cells = []

# ---------- Title ----------
cells.append(md(
    "# PSTU DataThon 2026 Vol 1 — Enhanced EDA & Feature Pruning",
    "",
    "Analyze the training data, detect unnecessary / duplicate columns, and produce a clean, reduced feature set that downstream models (LightGBM, XGBoost, CatBoost, MLP) can consume.",
    "",
    "**Inputs**",
    "- `train.csv` — ~60.6k rows x 350 anonymized numerical features + `TARGET`",
    "- `test.csv`  — ~75.8k rows + extra `id` column",
    "",
    "**What this notebook does**",
    "1. Loads `train.csv` / `test.csv` with memory-efficient dtypes.",
    "2. Profiles each column: dtype, missingness, cardinality, statistics, near-constant detection.",
    "3. Identifies **categorical-like** columns (the `feat_142 / 157 / 318 / 320 / 325 / 337` set) with prefix-aware labels (`PRD_`, `PRV_`, `PERF_`, `CH_`, `SEG_`, `OFC_`).",
    "4. Computes **Pearson** and **Spearman** correlations on numeric features; reports top |corr| pairs.",
    "5. Detects **duplicate columns** (exact duplicates) and **near-duplicate columns** (|corr| > 0.999).",
    "6. Detects **redundant columns** in two passes:",
    "   - High pairwise correlation (|Pearson| >= 0.95) — keep one representative per cluster.",
    "   - Target-uncorrelated columns (|point-biserial| < 0.005) — drop them as noise.",
    "7. Saves the reduced feature list to `enhanced_features.json` for downstream notebooks.",
    "",
    "**Outputs**",
    "- `enhanced_features.json` — `{kept_features, dropped_constant, dropped_dup, dropped_highcorr, dropped_uncorr, cat_cols, num_cols}`.",
    "- `enhanced_corr_top.csv` — the top |corr| pairs for human inspection.",
    "- `enhanced_dtypes.parquet` — memory-efficient cast of train (np.float32 + category dtypes).",
))

# ---------- 1. Imports ----------
cells.append(md("## 1. Imports & Configuration"))
cells.append(code(
    "import os, gc, json, time, warnings, hashlib\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "pd.set_option('display.max_columns', 100)\n",
    "pd.set_option('display.width', 200)\n",
    "pd.set_option('display.max_rows', 200)\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "sns.set_theme(style='whitegrid', context='notebook')\n",
    "\n",
    "from scipy.stats import pearsonr, spearmanr, pointbiserialr\n",
    "\n",
    "DATA = r'd:\\DS\\kaggle\\PSTU_Datathon'\n",
    "SEED = 42\n",
    "np.random.seed(SEED)\n",
    "\n",
    "# Thresholds (centralized so downstream notebooks can stay aligned)\n",
    "CORR_HIGH  = 0.95   # |Pearson| >= this -> near-duplicate cluster\n",
    "CORR_DUP   = 0.999  # |Pearson| >= this -> treat as exact duplicate\n",
    "CORR_UNCORR = 0.005 # |corr w/ TARGET| < this -> drop as noise\n",
    "MISSING_DROP = 0.95 # drop columns with >= 95% missing\n",
    "CONSTANT_DROP = 0.999  # drop columns where one value occupies >= 99.9% of rows\n",
    "\n",
    "print('pandas:', pd.__version__)\n",
    "print('numpy :', np.__version__)\n",
    "t0 = time.time()\n",
    "print(f'Config OK ({time.time()-t0:.2f}s)')\n",
))

# ---------- 2. Load ----------
cells.append(md("## 2. Load Data"))
cells.append(code(
    "t0 = time.time()\n",
    "# Two passes: first sample to learn dtypes, then full load with explicit dtypes.\n",
    "raw_train = pd.read_csv(f'{DATA}\\\\train.csv')\n",
    "raw_test  = pd.read_csv(f'{DATA}\\\\test.csv')\n",
    "print(f'loaded train={raw_train.shape}, test={raw_test.shape}  in {time.time()-t0:.1f}s')\n",
    "print(f'train mem: {raw_train.memory_usage(deep=True).sum()/1e6:.1f} MB')\n",
    "print(f'test  mem: {raw_test.memory_usage(deep=True).sum()/1e6:.1f} MB')\n",
    "\n",
    "print('\\n--- train head (first 5 cols / 3 rows) ---')\n",
    "display(raw_train.iloc[:3, :5])\n",
    "print('\\n--- train target balance ---')\n",
    "print(raw_train['TARGET'].value_counts(normalize=True).rename('frac'))\n",
    "print('\\n--- test id sample ---')\n",
    "print(raw_test['id'].head())\n",
))

# ---------- 3. Downcast dtypes ----------
cells.append(md("## 3. Memory-Efficient Dtype Cast"))
cells.append(code(
    "def downcast(df: pd.DataFrame) -> pd.DataFrame:\n",
    "    \"\"\"int64 -> int{int8/16/32}, float64 -> float32, keep object as object.\"\"\"\n",
    "    for c in df.columns:\n",
    "        s = df[c]\n",
    "        if s.dtype == 'int64':\n",
    "            mn, mx = s.min(), s.max()\n",
    "            if mn >= -128 and mx <= 127:\n",
    "                df[c] = s.astype('int8')\n",
    "            elif mn >= -32768 and mx <= 32767:\n",
    "                df[c] = s.astype('int16')\n",
    "            else:\n",
    "                df[c] = s.astype('int32')\n",
    "        elif s.dtype == 'float64':\n",
    "            df[c] = s.astype('float32')\n",
    "    return df\n",
    "\n",
    "t0 = time.time()\n",
    "train_n = raw_train.shape[0]\n",
    "test_n  = raw_test.shape[0]\n",
    "target = raw_train['TARGET'].astype('int8').values\n",
    "ids_test = raw_test['id'].values\n",
    "\n",
    "drop_cols = ['TARGET', 'id']\n",
    "feat_cols = [c for c in raw_train.columns if c not in drop_cols]\n",
    "print(f'# features: {len(feat_cols)} (train has {len(raw_train.columns)} cols incl. TARGET)')\n",
    "\n",
    "raw_train = downcast(raw_train)\n",
    "raw_test  = downcast(raw_test)\n",
    "print(f'train mem after downcast: {raw_train.memory_usage(deep=True).sum()/1e6:.1f} MB')\n",
    "print(f'test  mem after downcast: {raw_test.memory_usage(deep=True).sum()/1e6:.1f} MB')\n",
    "print(f'dtype counts: {raw_train[feat_cols].dtypes.value_counts().to_dict()}')\n",
    "print(f'downcast done in {time.time()-t0:.1f}s')\n",
))

# ---------- 4. Profile columns ----------
cells.append(md("## 4. Per-Column Profile"))
cells.append(code(
    "CAT_COLS = ['feat_142','feat_157','feat_318','feat_320','feat_325','feat_337']\n",
    "NUM_COLS = [c for c in feat_cols if c not in CAT_COLS]\n",
    "print(f'NUM_COLS: {len(NUM_COLS)}, CAT_COLS: {len(CAT_COLS)}')\n",
    "\n",
    "def profile(df: pd.DataFrame, cols: list) -> pd.DataFrame:\n",
    "    rows = []\n",
    "    n = len(df)\n",
    "    for c in cols:\n",
    "        s = df[c]\n",
    "        is_num = pd.api.types.is_numeric_dtype(s)\n",
    "        n_missing = int(s.isna().sum())\n",
    "        nunique = int(s.nunique(dropna=True))\n",
    "        rec = {\n",
    "            'col': c,\n",
    "            'dtype': str(s.dtype),\n",
    "            'is_numeric': is_num,\n",
    "            'n_missing': n_missing,\n",
    "            'missing_frac': n_missing / n,\n",
    "            'nunique': nunique,\n",
    "            'unique_frac': nunique / max(n - n_missing, 1),\n",
    "        }\n",
    "        if is_num and nunique > 0:\n",
    "            sv = s.dropna()\n",
    "            rec.update({\n",
    "                'min': float(sv.min()),\n",
    "                'max': float(sv.max()),\n",
    "                'mean': float(sv.mean()),\n",
    "                'std': float(sv.std()),\n",
    "                'skew': float(sv.skew()),\n",
    "            })\n",
    "        else:\n",
    "            rec.update({'min': np.nan, 'max': np.nan, 'mean': np.nan, 'std': np.nan, 'skew': np.nan})\n",
    "        rows.append(rec)\n",
    "    return pd.DataFrame(rows).set_index('col')\n",
    "\n",
    "t0 = time.time()\n",
    "prof = profile(raw_train, feat_cols)\n",
    "print(f'profiled {len(prof)} cols in {time.time()-t0:.1f}s')\n",
    "\n",
    "# Show the categorical columns\n",
    "print('\\n--- categorical profile ---')\n",
    "display(prof.loc[CAT_COLS])\n",
    "\n",
    "# Show numeric distribution summary\n",
    "print('\\n--- numeric profile (head) ---')\n",
    "display(prof.head(10))\n",
    "\n",
    "# Distribution of missingness\n",
    "print('\\n--- missingness buckets (numeric) ---')\n",
    "bins = [0, 0.01, 0.05, 0.20, 0.50, 0.95, 1.01]\n",
    "labels = ['0','<=1%','<=5%','<=20%','<=50%','<=100%']\n",
    "miss_bucket = pd.cut(prof.loc[NUM_COLS, 'missing_frac'], bins=bins, labels=labels, include_lowest=True)\n",
    "print(miss_bucket.value_counts().sort_index())\n",
))

# ---------- 5. Constant / near-constant ----------
cells.append(md("## 5. Constant & Near-Constant Columns"))
cells.append(code(
    "constant_cols = prof[(prof['nunique'] <= 1)].index.tolist()\n",
    "near_const_cols = prof[(prof['unique_frac'] >= CONSTANT_DROP) & (prof['nunique'] > 1)].index.tolist()\n",
    "high_missing_cols = prof[prof['missing_frac'] >= MISSING_DROP].index.tolist()\n",
    "\n",
    "print(f'constant (nunique<=1)        : {len(constant_cols)} {constant_cols[:10]}')\n",
    "print(f'near-constant (>={CONSTANT_DROP} unique_frac): {len(near_const_cols)}')\n",
    "print(f'high-missing (>={MISSING_DROP} missing)     : {len(high_missing_cols)} {high_missing_cols[:10]}')\n",
    "\n",
    "# Optional: drop these later, but keep them visible\n",
    "to_drop_constant = constant_cols + high_missing_cols\n",
    "print(f'\\nDrop list (constant + missing): {len(to_drop_constant)}')\n",
))

# ---------- 6. Correlation matrix ----------
cells.append(md("## 6. Correlation Analysis (Pearson & Spearman)"))
cells.append(code(
    "# Subsample for Spearman (~ 20k rows) — Spearman is O(n log n) but memory-cheap.\n",
    "# Pearson uses the full training set on numeric columns.\n",
    "t0 = time.time()\n",
    "X_num_full = raw_train[NUM_COLS].astype('float32').values\n",
    "\n",
    "# Pearson on full data\n",
    "print('computing Pearson corr (full train) on', X_num_full.shape, '...')\n",
    "pearson_corr = np.corrcoef(X_num_full, rowvar=False)\n",
    "pearson_corr = np.nan_to_num(pearson_corr, nan=0.0, posinf=0.0, neginf=0.0)\n",
    "print(f'  done in {time.time()-t0:.1f}s  shape={pearson_corr.shape}')\n",
    "\n",
    "# Spearman on a 20k subsample\n",
    "rng = np.random.default_rng(SEED)\n",
    "n_spearman = min(20000, X_num_full.shape[0])\n",
    "idx_s = rng.choice(X_num_full.shape[0], size=n_spearman, replace=False)\n",
    "X_sub = X_num_full[idx_s]\n",
    "print(f'computing Spearman corr on {n_spearman} rows ...')\n",
    "t0 = time.time()\n",
    "spearman_corr = pd.DataFrame(X_sub, columns=NUM_COLS).corr(method='spearman').values\n",
    "spearman_corr = np.nan_to_num(spearman_corr, nan=0.0, posinf=0.0, neginf=0.0)\n",
    "print(f'  done in {time.time()-t0:.1f}s')\n",
    "\n",
    "# Save corr matrices for reuse\n",
    "np.save(f'{DATA}\\\\pearson_corr.npy', pearson_corr.astype('float32'))\n",
    "np.save(f'{DATA}\\\\spearman_corr.npy', spearman_corr.astype('float32'))\n",
    "print('saved pearson_corr.npy and spearman_corr.npy')\n",
))

# ---------- 7. Top corr pairs ----------
cells.append(md("## 7. Top |Correlation| Pairs"))
cells.append(code(
    "def top_abs_pairs(M, cols, k=50, drop_diag=True):\n",
    "    n = M.shape[0]\n",
    "    iu = np.triu_indices(n, k=1 if drop_diag else 0)\n",
    "    vals = np.abs(M[iu])\n",
    "    order = np.argsort(-vals)[:k]\n",
    "    rec = pd.DataFrame({\n",
    "        'f1': [cols[i] for i in iu[0][order]],\n",
    "        'f2': [cols[j] for j in iu[1][order]],\n",
    "        'corr': M[iu[0][order], iu[1][order]],\n",
    "        'abs_corr': vals[order],\n",
    "    })\n",
    "    return rec\n",
    "\n",
    "top_pearson = top_abs_pairs(pearson_corr, NUM_COLS, k=50)\n",
    "top_spearman = top_abs_pairs(spearman_corr, NUM_COLS, k=50)\n",
    "\n",
    "print('--- top 25 Pearson pairs ---')\n",
    "display(top_pearson.head(25))\n",
    "print('\\n--- top 25 Spearman pairs ---')\n",
    "display(top_spearman.head(25))\n",
    "\n",
    "# Save for human review\n",
    "top_pearson.to_csv(f'{DATA}\\\\enhanced_corr_top.csv', index=False)\n",
    "print('wrote enhanced_corr_top.csv')\n",
))

# ---------- 8. Heatmap preview ----------
cells.append(md("## 8. Heatmap of the Most Correlated Block"))
cells.append(code(
    "# Pick the top 30 columns by abs correlation with the target, then show their pairwise heatmap.\n",
    "y = target.astype('float32')\n",
    "target_corr = np.array([np.corrcoef(X_num_full[:, i], y)[0, 1] for i in range(X_num_full.shape[1])])\n",
    "target_corr = np.nan_to_num(target_corr, nan=0.0)\n",
    "order = np.argsort(-np.abs(target_corr))[:30]\n",
    "top_cols = [NUM_COLS[i] for i in order]\n",
    "print('top 30 features by |corr| with TARGET:')\n",
    "for c, v in zip(top_cols, target_corr[order]):\n",
    "    print('  {:>10s}  {:+.4f}'.format(c, v))\n",
    "\n",
    "ix = [NUM_COLS.index(c) for c in top_cols]\n",
    "M = pd.DataFrame(pearson_corr[np.ix_(ix, ix)], index=top_cols, columns=top_cols)\n",
    "plt.figure(figsize=(13, 11))\n",
    "sns.heatmap(M, cmap='coolwarm', center=0, vmin=-1, vmax=1, square=True,\n",
    "            cbar_kws={'shrink': 0.7}, linewidths=0.2, linecolor='white')\n",
    "plt.title('Pearson corr — top 30 features by |corr with TARGET|')\n",
    "plt.tight_layout(); plt.show()\n",
))

# ---------- 9. Duplicate exact columns ----------
cells.append(md("## 9. Exact Duplicate Columns"))
cells.append(code(
    "# Hash each column to detect exact duplicates (also handles object dtype).\n",
    "def hash_columns(df: pd.DataFrame, cols: list) -> dict:\n",
    "    h = {}\n",
    "    for c in cols:\n",
    "        # Convert to bytes via numpy after fillna on object columns so NaN matches NaN\n",
    "        s = df[c]\n",
    "        if s.dtype == object:\n",
    "            arr = s.fillna('__nan__').astype(str).values\n",
    "        else:\n",
    "            arr = np.nan_to_num(s.values.astype('float64'), nan=np.nan)\n",
    "        h[c] = hashlib.md5(arr.tobytes()).hexdigest()\n",
    "    return h\n",
    "\n",
    "t0 = time.time()\n",
    "hashes = hash_columns(raw_train, feat_cols)\n",
    "from collections import defaultdict\n",
    "groups = defaultdict(list)\n",
    "for c, h in hashes.items():\n",
    "    groups[h].append(c)\n",
    "dup_groups = {h: cs for h, cs in groups.items() if len(cs) > 1}\n",
    "print(f'Found {len(dup_groups)} duplicate groups among {len(feat_cols)} cols ({time.time()-t0:.1f}s)')\n",
    "for h, cs in list(dup_groups.items())[:10]:\n",
    "    print(f'  hash {h[:8]}... -> {cs}')\n",
    "\n",
    "dropped_duplicates = []\n",
    "kept_dup_reps = []\n",
    "for h, cs in dup_groups.items():\n",
    "    # Keep the one with the highest |corr| with TARGET (or alphabetically first if tied).\n",
    "    cs_sorted = sorted(cs, key=lambda c: (-abs(target_corr[NUM_COLS.index(c)]) if c in NUM_COLS else 0, c))\n",
    "    keep = cs_sorted[0]\n",
    "    dropped_duplicates.extend(cs_sorted[1:])\n",
    "    kept_dup_reps.append(keep)\n",
    "print(f'\\nDrop {len(dropped_duplicates)} duplicate cols; keep {len(kept_dup_reps)} representatives.')\n",
))

# ---------- 10. Near-duplicate columns (corr >= 0.999) ----------
cells.append(md("## 10. Near-Duplicate Columns (|Pearson| ≥ 0.999)"))
cells.append(code(
    "# Treat |corr| >= CORR_DUP as duplicates (e.g. duplicates with NaN-induced jitter).\n",
    "iu = np.triu_indices(len(NUM_COLS), k=1)\n",
    "mask = np.abs(pearson_corr[iu]) >= CORR_DUP\n",
    "near_dup_pairs = pd.DataFrame({\n",
    "    'f1': [NUM_COLS[i] for i in iu[0][mask]],\n",
    "    'f2': [NUM_COLS[j] for j in iu[1][mask]],\n",
    "    'corr': pearson_corr[iu[0][mask], iu[1][mask]],\n",
    "})\n",
    "print(f'# near-duplicate pairs: {len(near_dup_pairs)}')\n",
    "display(near_dup_pairs.head(20))\n",
    "\n",
    "# Build a union-find so a column in 3+ clusters of 0.999+ is only dropped once\n",
    "parent = {c: c for c in NUM_COLS}\n",
    "def find(x):\n",
    "    while parent[x] != x:\n",
    "        parent[x] = parent[parent[x]]\n",
    "        x = parent[x]\n",
    "    return x\n",
    "def union(a, b):\n",
    "    ra, rb = find(a), find(b)\n",
    "    if ra != rb:\n",
    "        parent[ra] = rb\n",
    "for _, row in near_dup_pairs.iterrows():\n",
    "    union(row['f1'], row['f2'])\n",
    "\n",
    "clusters = defaultdict(list)\n",
    "for c in NUM_COLS:\n",
    "    clusters[find(c)].append(c)\n",
    "big_clusters = [cs for cs in clusters.values() if len(cs) > 1]\n",
    "print(f'\\n# clusters with >1 member: {len(big_clusters)}')\n",
    "for cs in big_clusters[:5]:\n",
    "    print(' ', cs)\n",
    "\n",
    "dropped_near_dup = set()\n",
    "for cs in big_clusters:\n",
    "    rep = sorted(cs, key=lambda c: (-abs(target_corr[NUM_COLS.index(c)]), c))[0]\n",
    "    for c in cs:\n",
    "        if c != rep:\n",
    "            dropped_near_dup.add(c)\n",
    "print(f'\\nDrop {len(dropped_near_dup)} near-duplicate cols (kept 1 per cluster).')\n",
))

# ---------- 11. High pairwise correlation clusters (>= 0.95) ----------
cells.append(md("## 11. High-Correlation Clusters (|Pearson| ≥ 0.95)"))
cells.append(code(
    "iu = np.triu_indices(len(NUM_COLS), k=1)\n",
    "mask = np.abs(pearson_corr[iu]) >= CORR_HIGH\n",
    "high_pairs = pd.DataFrame({\n",
    "    'f1': [NUM_COLS[i] for i in iu[0][mask]],\n",
    "    'f2': [NUM_COLS[j] for j in iu[1][mask]],\n",
    "    'corr': pearson_corr[iu[0][mask], iu[1][mask]],\n",
    "})\n",
    "print(f'# pairs with |corr| >= {CORR_HIGH}: {len(high_pairs)}')\n",
    "display(high_pairs.head(20))\n",
    "\n",
    "# Build clusters again (graph-based union-find)\n",
    "parent = {c: c for c in NUM_COLS}\n",
    "def find(x):\n",
    "    while parent[x] != x:\n",
    "        parent[x] = parent[parent[x]]\n",
    "        x = parent[x]\n",
    "    return x\n",
    "def union(a, b):\n",
    "    ra, rb = find(a), find(b)\n",
    "    if ra != rb:\n",
    "        parent[ra] = rb\n",
    "for _, row in high_pairs.iterrows():\n",
    "    union(row['f1'], row['f2'])\n",
    "clusters = defaultdict(list)\n",
    "for c in NUM_COLS:\n",
    "    clusters[find(c)].append(c)\n",
    "big_clusters = sorted([cs for cs in clusters.values() if len(cs) > 1], key=len, reverse=True)\n",
    "print(f'\\n# clusters with >1 member: {len(big_clusters)}')\n",
    "for cs in big_clusters[:8]:\n",
    "    print(f'  size {len(cs)}: {cs[:6]}{\"...\" if len(cs)>6 else \"\"}')\n",
    "\n",
    "# In each cluster, keep the one with the highest |corr| with TARGET.\n",
    "dropped_highcorr = set()\n",
    "for cs in big_clusters:\n",
    "    rep = sorted(cs, key=lambda c: (-abs(target_corr[NUM_COLS.index(c)]), c))[0]\n",
    "    for c in cs:\n",
    "        if c != rep:\n",
    "            dropped_highcorr.add(c)\n",
    "print(f'\\nDrop {len(dropped_highcorr)} cols from high-corr clusters (kept 1 per cluster).')\n",
))

# ---------- 12. Uncorrelated w/ TARGET ----------
cells.append(md("## 12. Target-Uncorrelated Columns"))
cells.append(code(
    "abs_t = np.abs(target_corr)\n",
    "uncorr_cols = [NUM_COLS[i] for i in np.where(abs_t < CORR_UNCORR)[0]]\n",
    "print(f'cols with |corr TARGET| < {CORR_UNCORR}: {len(uncorr_cols)}')\n",
    "print('  first 30:', uncorr_cols[:30])\n",
    "\n",
    "# Distribution of |corr| with target\n",
    "plt.figure(figsize=(8, 4))\n",
    "plt.hist(abs_t, bins=50, color='steelblue', edgecolor='white')\n",
    "plt.axvline(CORR_UNCORR, color='red', linestyle='--', label=f'threshold {CORR_UNCORR}')\n",
    "plt.xlabel('|pearson corr with TARGET|'); plt.ylabel('# features')\n",
    "plt.title('Distribution of |corr w/ TARGET| across numeric features')\n",
    "plt.legend(); plt.tight_layout(); plt.show()\n",
))

# ---------- 13. Categorical column sanity check ----------
cells.append(md("## 13. Categorical Column Consistency"))
cells.append(code(
    "# Check that the categorical columns have the same set of categories in train and test\n",
    "print('col         train_n    test_n    overlap_only_train   overlap_only_test')\n",
    "for c in CAT_COLS:\n",
    "    tr = set(raw_train[c].dropna().unique())\n",
    "    te = set(raw_test[c].dropna().unique())\n",
    "    only_tr = tr - te\n",
    "    only_te = te - tr\n",
    "    print('{:10s} {:>8d} {:>8d} {:>20d} {:>20d}'.format(c, len(tr), len(te), len(only_tr), len(only_te)))\n",
    "\n",
    "# Show example prefixes\n",
    "print('\\n--- prefix distribution in CAT_COLS ---')\n",
    "for c in CAT_COLS:\n",
    "    s = raw_train[c].dropna().astype(str)\n",
    "    pref = s.str.split('_').str[0].value_counts().head(3)\n",
    "    print('  {}: {}'.format(c, pref.to_dict()))\n",
))

# ---------- 14. Build final kept list ----------
cells.append(md("## 14. Build the Reduced Feature List"))
cells.append(code(
    "drop_constant = set(constant_cols) | set(high_missing_cols) | set(near_const_cols)\n",
    "drop_dup      = set(dropped_duplicates) | dropped_near_dup\n",
    "drop_highcorr = dropped_highcorr\n",
    "drop_uncorr   = set(uncorr_cols)\n",
    "\n",
    "keep_cols = [c for c in feat_cols if c not in (drop_constant | drop_dup | drop_highcorr | drop_uncorr)]\n",
    "\n",
    "print(f'original features : {len(feat_cols)}')\n",
    "print(f'drop constant     : {len(drop_constant)}')\n",
    "print(f'drop duplicate    : {len(drop_dup)}')\n",
    "print(f'drop high-corr    : {len(drop_highcorr)}')\n",
    "print(f'drop uncorr       : {len(drop_uncorr)}')\n",
    "print(f'kept columns      : {len(keep_cols)}')\n",
    "\n",
    "# Recompute categorical vs numeric within the kept columns\n",
    "kept_cat = [c for c in CAT_COLS if c in keep_cols]\n",
    "kept_num = [c for c in keep_cols if c not in kept_cat]\n",
    "print(f'  -> numeric: {len(kept_num)}, categorical: {len(kept_cat)}')\n",
    "\n",
    "summary = {\n",
    "    'data_dir': DATA,\n",
    "    'original_features': feat_cols,\n",
    "    'kept_features': keep_cols,\n",
    "    'kept_numeric': kept_num,\n",
    "    'kept_categorical': kept_cat,\n",
    "    'dropped_constant': sorted(drop_constant),\n",
    "    'dropped_dup': sorted(drop_dup),\n",
    "    'dropped_highcorr': sorted(drop_highcorr),\n",
    "    'dropped_uncorr': sorted(drop_uncorr),\n",
    "    'thresholds': {\n",
    "        'CORR_HIGH': CORR_HIGH, 'CORR_DUP': CORR_DUP,\n",
    "        'CORR_UNCORR': CORR_UNCORR, 'MISSING_DROP': MISSING_DROP,\n",
    "        'CONSTANT_DROP': CONSTANT_DROP,\n",
    "    },\n",
    "    'n_train': train_n, 'n_test': test_n,\n",
    "    'target_pos_rate': float(target.mean()),\n",
    "}\n",
    "with open(f'{DATA}\\\\enhanced_features.json', 'w', encoding='utf-8') as f:\n",
    "    json.dump(summary, f, indent=2)\n",
    "print('\\nwrote enhanced_features.json')\n",
))

# ---------- 15. Build the reduced parquet ----------
cells.append(md("## 15. Save the Reduced Train/Test Parquet"))
cells.append(code(
    "t0 = time.time()\n",
    "train_kept = raw_train[keep_cols + ['TARGET']].copy()\n",
    "test_kept  = raw_test[keep_cols + ['id']].copy()\n",
    "\n",
    "# Cast categorical columns to pandas category\n",
    "for c in kept_cat:\n",
    "    train_kept[c] = train_kept[c].astype('category')\n",
    "    test_kept[c]  = test_kept[c].astype('category')\n",
    "\n",
    "train_kept.to_parquet(f'{DATA}\\\\enhanced_train.parquet', index=False)\n",
    "test_kept.to_parquet(f'{DATA}\\\\enhanced_test.parquet',  index=False)\n",
    "print(f'wrote enhanced_train.parquet {train_kept.shape}  ({time.time()-t0:.1f}s)')\n",
    "print(f'wrote enhanced_test.parquet  {test_kept.shape}')\n",
    "\n",
    "print(f'train mem: {train_kept.memory_usage(deep=True).sum()/1e6:.1f} MB')\n",
    "print(f'kept feature summary:')\n",
    "print(f'  numeric     : {len(kept_num)}')\n",
    "print(f'  categorical : {len(kept_cat)}')\n",
))

# ---------- 16. Quick LGBM sanity check ----------
cells.append(md("## 16. Sanity Check — LightGBM with the Reduced Feature Set"))
cells.append(code(
    "import lightgbm as lgb\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.metrics import f1_score, roc_auc_score\n",
    "\n",
    "X = train_kept.drop(columns=['TARGET']).copy()\n",
    "y = train_kept['TARGET'].astype('int8').values\n",
    "X_test = test_kept.drop(columns=['id']).copy()\n",
    "ids_test = test_kept['id'].values\n",
    "\n",
    "# Use categorical column names directly\n",
    "params = dict(\n",
    "    objective='binary', metric='binary_logloss', learning_rate=0.05,\n",
    "    num_leaves=63, min_data_in_leaf=40, feature_fraction=0.8,\n",
    "    bagging_fraction=0.8, bagging_freq=1, lambda_l2=1.0,\n",
    "    verbose=-1, n_jobs=-1, is_unbalance=True, seed=SEED,\n",
    ")\n",
    "skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=SEED)\n",
    "oof = np.zeros(len(y))\n",
    "test_pred = np.zeros(len(X_test))\n",
    "fold_iters = []\n",
    "for fold, (tri, vli) in enumerate(skf.split(X, y), 1):\n",
    "    d_tr = lgb.Dataset(X.iloc[tri], y[tri], categorical_feature=kept_cat, free_raw_data=False)\n",
    "    d_vl = lgb.Dataset(X.iloc[vli], y[vli], categorical_feature=kept_cat, reference=d_tr, free_raw_data=False)\n",
    "    m = lgb.train(params, d_tr, num_boost_round=600, valid_sets=[d_vl],\n",
    "                  callbacks=[lgb.early_stopping(80, verbose=False), lgb.log_evaluation(0)])\n",
    "    oof[vli] = m.predict(X.iloc[vli], num_iteration=m.best_iteration)\n",
    "    test_pred += m.predict(X_test, num_iteration=m.best_iteration) / skf.n_splits\n",
    "    fold_iters.append(m.best_iteration)\n",
    "    f1 = f1_score(y[vli], (oof[vli]>=0.5).astype(int), average='macro')\n",
    "    auc = roc_auc_score(y[vli], oof[vli])\n",
    "    print('  fold {} best_iter={}  f1@0.5={:.4f}  auc={:.4f}'.format(fold, m.best_iteration, f1, auc))\n",
    "\n",
    "# Tune threshold quickly\n",
    "best_f1, best_thr = 0.0, 0.5\n",
    "for thr in np.linspace(0.05, 0.95, 19):\n",
    "    f1 = f1_score(y, (oof>=thr).astype(int), average='macro')\n",
    "    if f1 > best_f1:\n",
    "        best_f1, best_thr = f1, thr\n",
    "print('\\nOOF macroF1 @ best_thr={:.3f} -> {:.4f}'.format(best_thr, best_f1))\n",
    "print('OOF AUC                  -> {:.4f}'.format(roc_auc_score(y, oof)))\n",
    "\n",
    "# Save used thresholds/feature counts for downstream reuse\n",
    "with open(f'{DATA}\\\\enhanced_best_lgbm.json', 'w', encoding='utf-8') as f:\n",
    "    json.dump({\n",
    "        'best_threshold': float(best_thr),\n",
    "        'best_macro_f1': float(best_f1),\n",
    "        'oof_auc': float(roc_auc_score(y, oof)),\n",
    "        'n_features': len(keep_cols),\n",
    "        'mean_iters': int(np.mean(fold_iters)),\n",
    "    }, f, indent=2)\n",
    "print('wrote enhanced_best_lgbm.json')\n",
    "\n",
    "# Save raw probabilities for downstream stacking / submission\n",
    "np.savez(f'{DATA}\\\\enhanced_lgbm_preds.npz',\n",
    "         oof=oof.astype('float32'),\n",
    "         test_pred=test_pred.astype('float32'),\n",
    "         ids=ids_test)\n",
    "print('wrote enhanced_lgbm_preds.npz')\n",
))

# ---------- 17. Build submission CSV ----------
cells.append(md("## 17. Generate Submission CSV"))
cells.append(code(
    "from sklearn.metrics import f1_score\n",
    "\n",
    "# Re-load the sample submission to mirror its exact id ordering.\n",
    "sample_sub = pd.read_csv(f'{DATA}\\\\sample_submission.csv')\n",
    "print('sample_submission shape:', sample_sub.shape)\n",
    "print('sample_submission head:')\n",
    "display(sample_sub.head())\n",
    "\n",
    "# Map our test scores back into the sample_submission id order\n",
    "pred_map = dict(zip(ids_test, test_pred))\n",
    "sample_sub = sample_sub.copy()\n",
    "sample_sub['score'] = sample_sub['id'].map(pred_map).astype('float32')\n",
    "missing = sample_sub['score'].isna().sum()\n",
    "print('\\nids in sample missing from test_pred:', missing)\n",
    "assert missing == 0, 'Sample submission ids must all be present in the test predictions!'\n",
    "\n",
    "# Pick the threshold from the OOF tuning. Fall back to 0.5 if NaN.\n",
    "final_thr = float(best_thr) if not np.isnan(best_thr) else 0.5\n",
    "print('using threshold =', final_thr)\n",
    "\n",
    "# helpers\n",
    "def top_q_predict(scores, q):\n",
    "    n = len(scores); k = max(1, int(round(n * q)))\n",
    "    thr = np.partition(scores, n - k)[n - k]\n",
    "    return (scores >= thr).astype('int8'), float(thr)\n",
    "\n",
    "def write_sub(ids, scores, target, path, q=None, thr=None):\n",
    "    if q is not None:\n",
    "        pred, used_thr = top_q_predict(scores, q)\n",
    "    else:\n",
    "        pred = (scores >= thr).astype('int8')\n",
    "        used_thr = float(thr)\n",
    "    sub = pd.DataFrame({'id': ids, 'TARGET': pred})\n",
    "    sub.to_csv(path, index=False)\n",
    "    return sub, used_thr, int(pred.sum())\n",
    "\n",
    "print('\\n--- writing submission candidates ---')\n",
    "sub_default, used_thr, npos = write_sub(\n",
    "    sample_sub['id'].values, sample_sub['score'].values,\n",
    "    sample_sub['TARGET'].values,\n",
    "    f'{DATA}\\\\submission_enhanced.csv', thr=final_thr,\n",
    ")\n",
    "print('  submission_enhanced.csv  thr={:.4f}  positives={}/{} ({:.2f}%)'.format(\n",
    "    used_thr, npos, len(sub_default), npos/len(sub_default)*100))\n",
    "\n",
    "# Top-q alternatives (mirrors the candidates used in build_nb3_v3.py)\n",
    "for q in [0.05, 0.15, 0.30, 0.50, 0.70]:\n",
    "    sub, used_thr, npos = write_sub(\n",
    "        sample_sub['id'].values, sample_sub['score'].values,\n",
    "        sample_sub['TARGET'].values,\n",
    "        f'{DATA}\\\\submission_enhanced_q{int(q*100):02d}.csv',\n",
    "        q=q,\n",
    "    )\n",
    "    print('  submission_enhanced_q{:02d}.csv  q={:.2f}  thr={:.4f}  positives={} ({:.2f}%)'.format(\n",
    "        int(q*100), q, used_thr, npos, npos/len(sub)*100))\n",
    "\n",
    "# Final sanity checks against the sample format\n",
    "final_sub = pd.read_csv(f'{DATA}\\\\submission_enhanced.csv')\n",
    "print('\\n--- final submission sanity check ---')\n",
    "print('shape:', final_sub.shape)\n",
    "print('cols :', list(final_sub.columns))\n",
    "print('id min/max:', final_sub['id'].min(), final_sub['id'].max())\n",
    "print('id unique :', final_sub['id'].nunique())\n",
    "print('TARGET dist:', final_sub['TARGET'].value_counts(dropna=False).to_dict())\n",
    "print('NaN TARGET :', final_sub['TARGET'].isna().sum())\n",
    "print('ids in same order as sample:', (final_sub['id'].values == sample_sub['id'].values).all())\n",
))

# ---------- 18. Summary ----------
cells.append(md(
    "## 18. Summary",
    "",
    "**Detected in this dataset** (numbers are populated at runtime in cell 14)",
    "",
    "- 350 raw features (excluding `TARGET`, `id`).",
    "- Categorical column candidates: `feat_142, feat_157, feat_318, feat_320, feat_325, feat_337` (validated by prefix and small cardinality).",
    "- Constant / high-missing columns dropped: see cell 5.",
    "- Exact & near-duplicate columns dropped: see cells 9-10 (unique representative kept per cluster).",
    "- High pairwise correlation columns dropped (|Pearson| >= 0.95): see cell 11.",
    "- Target-uncorrelated columns dropped (|corr| < 0.005): see cell 12.",
    "- **Final kept feature count**: see cell 14.",
    "",
    "**Output artifacts**",
    "",
    "- `enhanced_features.json` — full kept / dropped lists + thresholds.",
    "- `enhanced_corr_top.csv` — top 50 |corr| pairs sorted by magnitude.",
    "- `enhanced_train.parquet` / `enhanced_test.parquet` — reduced cast dataframes, ready for downstream models.",
    "- `enhanced_best_lgbm.json` — sanity-check OOF best threshold + Macro F1.",
    "- `enhanced_lgbm_preds.npz` — OOF + test probabilities from the sanity-check LGBM (cells 16-17).",
    "- `submission_enhanced.csv` — default binary submission (threshold-tuned on OOF).",
    "- `submission_enhanced_q{05,15,30,50,70}.csv` — top-q alternative submissions for LB A/B testing.",
    "- `pearson_corr.npy` / `spearman_corr.npy` — full correlation matrices for custom diagnostic work.",
    "",
    "Downstream notebooks can simply load `enhanced_features.json` to know which columns to use, and read `enhanced_train.parquet` / `enhanced_test.parquet` for plug-and-play training. The default submission lives at `submission_enhanced.csv`.",
))



# ---------- Write notebook ----------
nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}
NB_PATH.write_text(json.dumps(nb, indent=1), encoding='utf-8')
print(f'wrote {NB_PATH} with {len(cells)} cells')
